language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - TYPO3_BRANCH=master

before_script:
  - npm install -g gulp
  - npm install
  - composer install --dev
  - cd ..
  - git clone --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv newsletter typo3conf/ext/

script:
  - cd typo3conf/ext/newsletter && gulp && cd ../../../
  - ./bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c typo3conf/ext/news/Tests/Build/UnitTests.xml

after_script:
  - echo "Uploading code coverage results";
  - cp -R typo3conf/ext/newsletter/.git .
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
